// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfLiJCLRQXPHAN9c4FeVgLbwLvUu482bI',
    appId: '1:571620415205:web:71553eb17c521be6e0e60c',
    messagingSenderId: '571620415205',
    projectId: 'notes-flutter-349de',
    authDomain: 'notes-flutter-349de.firebaseapp.com',
    storageBucket: 'notes-flutter-349de.firebasestorage.app',
    measurementId: 'G-1R9TWYN0PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevKE2ITzNH053Aild0Ad2kTAALpIiVVU',
    appId: '1:571620415205:android:477454e441586f7ae0e60c',
    messagingSenderId: '571620415205',
    projectId: 'notes-flutter-349de',
    storageBucket: 'notes-flutter-349de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRkK_XEnkzfPIjpkUt-glU2cY_XvvlBcA',
    appId: '1:571620415205:ios:bc202e395dfda35ce0e60c',
    messagingSenderId: '571620415205',
    projectId: 'notes-flutter-349de',
    storageBucket: 'notes-flutter-349de.firebasestorage.app',
    iosBundleId: 'com.example.secureNotesFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRkK_XEnkzfPIjpkUt-glU2cY_XvvlBcA',
    appId: '1:571620415205:ios:bc202e395dfda35ce0e60c',
    messagingSenderId: '571620415205',
    projectId: 'notes-flutter-349de',
    storageBucket: 'notes-flutter-349de.firebasestorage.app',
    iosBundleId: 'com.example.secureNotesFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfLiJCLRQXPHAN9c4FeVgLbwLvUu482bI',
    appId: '1:571620415205:web:8c596d96500b1f0de0e60c',
    messagingSenderId: '571620415205',
    projectId: 'notes-flutter-349de',
    authDomain: 'notes-flutter-349de.firebaseapp.com',
    storageBucket: 'notes-flutter-349de.firebasestorage.app',
    measurementId: 'G-C47CGPEM5K',
  );
}
